name: Get Feed

on:
  schedule:
    - cron: '30 12 * * *' # Runs daily at 12:30 UTC
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDS_DATABASE_ID: ${{ secrets.NOTION_FEEDS_DATABASE_ID }}
      RUN_FREQUENCY: 86400 # in seconds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Latest version of checkout action
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Latest version of setup-node action
        with:
          node-version: 20 # Explicitly set Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Fetch and Run Notion Feed Script
        run: |
          curl -o index.js https://raw.githubusercontent.com/ravgeetdhillon/notion-feeder/build/dist/index.js
          node index.js
